[package]
name = "abc73c"
version = "0.1.0"
authors = ["hitoyozake <mikoto_1122@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
